"""recreation of all migrations to suit pg and mysql

Revision ID: cd68c92b9b9c
Revises:
Create Date: 2026-02-22 04:00:49.843249+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import database

# revision identifiers, used by Alembic.
revision: str = "cd68c92b9b9c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_logs",
        sa.Column("decision_log_id", sa.String(length=255), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=True),
        sa.Column("operation", sa.String(length=50), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("database", sa.String(length=255), nullable=True),
        sa.Column("schema", sa.String(length=255), nullable=True),
        sa.Column("table", sa.String(length=255), nullable=True),
        sa.Column("column", sa.String(length=255), nullable=True),
        sa.Column("permitted", sa.Boolean(), nullable=True),
        sa.Column("expression", sa.String(length=2048), nullable=True),
        sa.Column(
            "timestamp",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("decision_log_id"),
    )
    op.create_table(
        "ingestion_processes",
        sa.Column(
            "ingestion_process_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("object_type", sa.String(length=64), nullable=True),
        sa.Column(
            "started_at",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("log", sa.String(length=4096), nullable=True),
        sa.PrimaryKeyConstraint("ingestion_process_id"),
    )
    op.create_table(
        "opa_bundles",
        sa.Column("opa_bundle_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform", sa.String(length=100), nullable=True),
        sa.Column("e_tag", sa.String(length=255), nullable=True),
        sa.Column("bundle_filename", sa.String(length=512), nullable=True),
        sa.Column("bundle_directory", sa.String(length=1024), nullable=True),
        sa.Column("policy_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "record_updated_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("opa_bundle_id"),
    )
    op.create_table(
        "principal_attributes",
        sa.Column(
            "principal_attribute_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("fq_name", sa.String(length=512), nullable=True),
        sa.Column("attribute_key", sa.String(length=255), nullable=True),
        sa.Column("attribute_value", sa.String(length=1024), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "record_updated_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("principal_attribute_id"),
    )
    op.create_table(
        "principal_attributes_history",
        sa.Column("principal_attribute_id", sa.Integer(), nullable=True),
        sa.Column("fq_name", sa.String(length=512), nullable=True),
        sa.Column("attribute_key", sa.String(length=255), nullable=True),
        sa.Column("attribute_value", sa.String(length=1024), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "record_updated_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("history_id", sa.String(length=50), nullable=False),
        sa.Column(
            "history_record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("history_change_operation", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("history_id"),
    )
    op.create_table(
        "principal_attributes_stg",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fq_name", sa.String(length=512), nullable=True),
        sa.Column("attribute_key", sa.String(length=255), nullable=True),
        sa.Column("attribute_value", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "principal_groups",
        sa.Column(
            "principal_group_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("fq_name", sa.String(length=512), nullable=True),
        sa.Column("source_type", sa.String(length=100), nullable=True),
        sa.Column("source_uid", sa.String(length=255), nullable=True),
        sa.Column("scim_payload", sa.JSON(), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "record_updated_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("principal_group_id"),
    )
    op.create_table(
        "principal_groups_history",
        sa.Column("principal_group_id", sa.Integer(), nullable=True),
        sa.Column("fq_name", sa.String(length=512), nullable=True),
        sa.Column("members", database.src.array.StringArray(), nullable=True),
        sa.Column("source_type", sa.String(length=100), nullable=True),
        sa.Column("source_uid", sa.String(length=255), nullable=True),
        sa.Column("scim_payload", sa.JSON(), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "record_updated_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("history_id", sa.String(length=50), nullable=False),
        sa.Column(
            "history_record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("history_change_operation", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("history_id"),
    )
    op.create_table(
        "principals",
        sa.Column("principal_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fq_name", sa.String(length=512), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("user_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("source_type", sa.String(length=100), nullable=True),
        sa.Column("source_uid", sa.String(length=255), nullable=True),
        sa.Column("scim_payload", sa.JSON(), nullable=True),
        sa.Column("entitlements", database.src.array.StringArray(), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "record_updated_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("principal_id"),
    )
    op.create_table(
        "principals_history",
        sa.Column("principal_id", sa.Integer(), nullable=True),
        sa.Column("fq_name", sa.String(length=512), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("user_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("source_type", sa.String(length=100), nullable=True),
        sa.Column("source_uid", sa.String(length=255), nullable=True),
        sa.Column("scim_payload", sa.JSON(), nullable=True),
        sa.Column("entitlements", database.src.array.StringArray(), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "record_updated_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("history_id", sa.String(length=50), nullable=False),
        sa.Column(
            "history_record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("history_change_operation", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("history_id"),
    )
    op.create_table(
        "principals_staging",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fq_name", sa.String(length=512), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("user_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resource_attributes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fq_name", sa.String(length=512), nullable=True),
        sa.Column("attribute_key", sa.String(length=255), nullable=True),
        sa.Column("attribute_value", sa.String(length=2048), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "record_updated_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resource_attributes_history",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("fq_name", sa.String(length=512), nullable=True),
        sa.Column("attribute_key", sa.String(length=255), nullable=True),
        sa.Column("attribute_value", sa.String(length=2048), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "record_updated_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("history_id", sa.String(length=50), nullable=False),
        sa.Column(
            "history_record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("history_change_operation", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("history_id"),
    )
    op.create_table(
        "resource_attributes_stg",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fq_name", sa.String(length=512), nullable=True),
        sa.Column("attribute_key", sa.String(length=255), nullable=True),
        sa.Column("attribute_value", sa.String(length=2048), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fq_name", sa.String(length=512), nullable=True),
        sa.Column("platform", sa.String(length=100), nullable=True),
        sa.Column("object_type", sa.String(length=100), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "record_updated_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resources_history",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("fq_name", sa.String(length=512), nullable=True),
        sa.Column("platform", sa.String(length=100), nullable=True),
        sa.Column("object_type", sa.String(length=100), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "record_updated_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("history_id", sa.String(length=50), nullable=False),
        sa.Column(
            "history_record_created_date",
            database.src.datetime_utc.DateTimeUTC(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("history_change_operation", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("history_id"),
    )
    op.create_table(
        "resources_stg",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fq_name", sa.String(length=512), nullable=True),
        sa.Column("platform", sa.String(length=100), nullable=True),
        sa.Column("object_type", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "principal_group_members",
        sa.Column(
            "principal_group_member_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("principal_group_id", sa.Integer(), nullable=False),
        sa.Column("member_fq_name", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_group_id"],
            ["principal_groups.principal_group_id"],
        ),
        sa.PrimaryKeyConstraint("principal_group_member_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("principal_group_members")
    op.drop_table("resources_stg")
    op.drop_table("resources_history")
    op.drop_table("resources")
    op.drop_table("resource_attributes_stg")
    op.drop_table("resource_attributes_history")
    op.drop_table("resource_attributes")
    op.drop_table("principals_staging")
    op.drop_table("principals_history")
    op.drop_table("principals")
    op.drop_table("principal_groups_history")
    op.drop_table("principal_groups")
    op.drop_table("principal_attributes_stg")
    op.drop_table("principal_attributes_history")
    op.drop_table("principal_attributes")
    op.drop_table("opa_bundles")
    op.drop_table("ingestion_processes")
    op.drop_table("decision_logs")
    # ### end Alembic commands ###
